version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MatchingEngine"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1juisyo14elnf"
s3_prefix = "MatchingEngine"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
